### PR TITLE
added option to select 16 input channels

### LINKED ISSUE #7: Please add support for 16x16 matrix
Currently the module only supports 16 out 8 in, not 16x16

### PR DESCRIPTION
**Pull request by sychron**
Enhanced the array of options for the input channels dropdown to include 
id: 16, label: 16
to add support for the tesmart 16x16 matrix

fixes #7

### CODE REVIEW

**Comment by mareeekkkk** [comment]
This does not seem to be updated in 3.0.0 nor 3.1.0+6056.
The dropdown still only gives the options "4" & "8".

**Comment by josephdadams** [comment]
The module needs to be upgraded to the new companion v3 API before we can do anything else with it. I thought I had pointed this out somewhere, perhaps on slack.

https://github.com/bitfocus/companion-module-base/wiki/Upgrading-a-module-built-for-Companion-2.x

A module this simple should not take very long to convert.

**Comment by mareeekkkk** [comment]
@sychron would really appreciate the work, so we can use the missing 8 outputs in our studio!
Thank you

**Comment by sychron** [comment]
> @sychron would really appreciate the work, so we can use the missing 8 outputs in our studio! Thank you

I am not the maintainer of the original repository and just did the modification for 16 channels. 
I don't know the API changes and which adaptions have to be made to the original plugin, so I'm currently waiting for that to happen, too.

**Comment by josephdadams** [comment]
If you guys are willing to throw some money at it, I can convert it for you. Send me an email - it's on my [Github profile](https://github.com/josephdadams).

**Comment by josephdadams** [comment]
hey friends, I upgraded the module to v3 for you:

https://github.com/bitfocus/companion-bundled-modules/actions/runs/5757937186

**Pull request merged**
