### PR TITLE
fix(manisfest): correct name in package.json/README.md

### PR DESCRIPTION
**Pull request by estilles**
Updated name from `tesmart-hdmi-matrix` to `tesmart-hdmimatrix`

Resolves bitfocus#2

Signed-off-by: Johnny Estilles <johnny@estilles.com>

### CODE REVIEW

**Comment by JTF4** [comment]
I'm not apposed to changing the name. 

I'm just curious if there's a particular reason? I just want to know for future modules that I make.

**Comment by estilles** [comment]
> I'm not apposed to changing the name.
> 
> I'm just curious if there's a particular reason? I just want to know for future modules that I make.

The name in the manifest (package.json) has to match the last part of the name of the repo, otherwise the module will not load (See reported issue #2).

In other words, ff the name of the name of the repo is `companion-module-tesmart-hdmimatrix` then the `name` in `package.json` needs to be `tesmart-hdmimatrix`.

I changed the name on the README.md as well just so they would match.

**Comment by JTF4** [comment]
Ahhhh! I see. So its more of a I have the dumb moment.

**Comment by estilles** [comment]
> Ahhhh! I see. So its more of a I have the dumb moment.

No worries. It happens to all of us. :-)

Is this module ready to be merged into the Companion core?

**Comment by JTF4** [comment]
Yes

**Pull request merged**
